version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    user: root
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
      EMAILABLE_REPORT_CSS_CDN: "https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.css"
      EMAILABLE_REPORT_TITLE: "efe"
      SECURITY_USER: "hasanefeavc"
      SECURITY_PASS: "123"
      SECURITY_ENABLED: 1
      SERVER_URL: "https://www.google.com/"
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"